#!/usr/bin/env node
/**
 * Figma Design Token Importer — Colour Styles edition
 * ─────────────────────────────────────────────────────────────────────────────
 * Uses the standard Figma file-content API (scope: "file_content:read") to
 * extract every named SOLID colour style from the file, then writes:
 *   src/tokens/color-primitives.js  — all colours keyed by style name
 *   src/tokens/color-tokens.js      — semantic aliases (styles whose names
 *                                     contain semantic keywords, e.g. bg/text/
 *                                     border, point at matching primitives)
 *
 * Usage:
 *   node scripts/figma-import.mjs <FIGMA_FILE_KEY> <FIGMA_PERSONAL_TOKEN>
 *
 * Required token scope: "Read the contents of and render images from files"
 *
 * Node 18+ (native fetch).
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname }         from 'path'
import { fileURLToPath }            from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT       = resolve(__dirname, '..')
const TOKENS_DIR = resolve(ROOT, 'src/tokens')

// ── Helpers ────────────────────────────────────────────────────────────────

function rgbaToHex({ r, g, b, a = 1 }) {
  const c = (n) => Math.round(n * 255).toString(16).padStart(2, '0').toUpperCase()
  const hex = `#${c(r)}${c(g)}${c(b)}`
  return Math.round(a * 255) < 255 ? `${hex}${c(a)}` : hex
}

/** "Colors/Navy/500" → "navy-500", "Semantic/Background/Default" → "background-default" */
function normaliseName(name) {
  return name
    .replace(/^colou?rs?\//i, '')   // strip leading "Colors/" / "Colour/"
    .replace(/\//g, '-')            // slashes → hyphens
    .replace(/\s+/g, '-')           // spaces → hyphens
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '')     // strip everything else
    .replace(/-+/g, '-')            // collapse multiple hyphens
    .replace(/^-|-$/g, '')          // trim leading/trailing hyphens
}

/** Depth-first traversal; calls visitor(node) on every node */
function traverse(node, visitor) {
  visitor(node)
  if (Array.isArray(node.children)) {
    for (const child of node.children) traverse(child, visitor)
  }
}

function banner(source) {
  return [
    '// AUTO-GENERATED by scripts/figma-import.mjs — DO NOT EDIT MANUALLY',
    `// Last synced: ${new Date().toISOString()}`,
    `// Source file: ${source}`,
  ].join('\n')
}

// ── Semantic keyword detection ────────────────────────────────────────────

const SEMANTIC_KEYWORDS = [
  'background', 'bg',
  'text', 'foreground', 'fg',
  'border', 'outline', 'stroke',
  'surface', 'overlay',
  'success', 'error', 'warning', 'info',
  'disabled', 'hover', 'active', 'focus',
  'primary', 'secondary', 'accent', 'brand',
  'inverse', 'muted', 'subtle', 'emphasis',
]

function isSemantic(name) {
  const lower = name.toLowerCase()
  return SEMANTIC_KEYWORDS.some((kw) => lower.includes(kw))
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const [,, fileKey, figmaToken] = process.argv

  if (!fileKey || !figmaToken) {
    console.error('Usage: node scripts/figma-import.mjs <FIGMA_FILE_KEY> <FIGMA_PERSONAL_TOKEN>')
    process.exit(1)
  }

  console.log(`\n🎨  Fetching Figma file: ${fileKey}\n`)

  // ── 1. Fetch the full file ──────────────────────────────────────────────
  let data
  try {
    const res = await fetch(`https://api.figma.com/v1/files/${fileKey}`, {
      headers: { 'X-Figma-Token': figmaToken },
    })

    if (!res.ok) {
      const body = await res.text()
      console.error(`Figma API error ${res.status}:`, body)
      if (res.status === 403) {
        console.error('\n⚠️  Make sure your token has the "file_content:read" scope.')
        console.error('   Figma → Account Settings → Personal Access Tokens')
        console.error('   Enable: "Read the contents of and render images from files"')
      }
      process.exit(1)
    }

    data = await res.json()
  } catch (err) {
    console.error('Network error:', err.message)
    process.exit(1)
  }

  // ── 2. Build a registry of FILL styles from the top-level styles map ────
  //    styles: { styleId: { name, styleType, ... } }
  const fillStyleRegistry = {}
  for (const [id, style] of Object.entries(data.styles ?? {})) {
    if (style.styleType === 'FILL') {
      fillStyleRegistry[id] = { name: style.name, hex: null }
    }
  }

  const totalFillStyles = Object.keys(fillStyleRegistry).length
  console.log(`  Fill styles declared in file: ${totalFillStyles}`)

  if (totalFillStyles === 0) {
    console.warn('\n⚠️  No FILL colour styles found in this Figma file.')
    console.warn('   Make sure colour styles are defined (not just local fills).')
    console.warn('   The existing src/tokens/color-primitives.js is unchanged.\n')
    process.exit(0)
  }

  // ── 3. Traverse document to find actual fill colours ───────────────────
  //    Nodes that USE a named style carry both:
  //      node.styles.fill  → styleId
  //      node.fills[0]     → { type: "SOLID", color: { r, g, b, a } }
  let nodesScanned = 0

  traverse(data.document, (node) => {
    nodesScanned++
    const styleId = node.styles?.fill
    if (!styleId || !fillStyleRegistry[styleId]) return
    if (fillStyleRegistry[styleId].hex !== null) return // already resolved

    const fill = node.fills?.[0]
    if (fill?.type === 'SOLID' && fill.color) {
      fillStyleRegistry[styleId].hex = rgbaToHex(fill.color)
    }
  })

  console.log(`  Nodes scanned        : ${nodesScanned.toLocaleString()}`)

  const resolved   = Object.values(fillStyleRegistry).filter((s) => s.hex !== null)
  const unresolved = Object.values(fillStyleRegistry).filter((s) => s.hex === null)

  console.log(`  Colours resolved     : ${resolved.length}`)
  if (unresolved.length > 0) {
    console.log(`  Could not resolve    : ${unresolved.length}`)
    unresolved.forEach((s) => console.log(`    ⚠️  "${s.name}" — no SOLID fill node found`))
  }

  if (resolved.length === 0) {
    console.error('\n❌  No colours could be resolved. Aborting — token files unchanged.')
    process.exit(1)
  }

  // ── 4. Separate primitives and semantic tokens ─────────────────────────
  const primitiveEntries = []   // { key, hex }
  const semanticEntries  = []   // { key, hex, originalName }

  for (const { name, hex } of resolved) {
    const key = normaliseName(name)
    if (!key) continue
    if (isSemantic(name)) {
      semanticEntries.push({ key, hex, originalName: name })
    } else {
      primitiveEntries.push({ key, hex })
    }
  }

  // Sort for readability
  primitiveEntries.sort((a, b) => a.key.localeCompare(b.key))
  semanticEntries.sort((a, b) => a.key.localeCompare(b.key))

  // ── 5. Write color-primitives.js ──────────────────────────────────────
  mkdirSync(TOKENS_DIR, { recursive: true })

  // Include semantic colours in primitives too (as direct hex, for fallback)
  const figmaEntries = [
    ...primitiveEntries,
    ...semanticEntries.map(({ key, hex }) => ({ key, hex })),
  ].sort((a, b) => a.key.localeCompare(b.key))

  // Production palette — these are always kept as the base so the site never breaks.
  // When Figma fully defines these colours, remove entries from here that match Figma keys.
  const productionPalette = [
    // Neutrals
    { key: 'neutral-0',   hex: '#FFFFFF' },
    { key: 'neutral-50',  hex: '#F8FAFC' },
    { key: 'neutral-100', hex: '#E2E8F0' },
    { key: 'neutral-200', hex: '#CBD5E1' },
    { key: 'neutral-300', hex: '#94A3B8' },
    { key: 'neutral-400', hex: '#64748B' },
    { key: 'neutral-500', hex: '#475569' },
    { key: 'neutral-600', hex: '#334155' },
    { key: 'neutral-700', hex: '#1E293B' },
    { key: 'neutral-800', hex: '#0F172A' },
    { key: 'neutral-900', hex: '#020617' },
    // Navy
    { key: 'navy-50',  hex: '#E8EEF4' },
    { key: 'navy-100', hex: '#C5D3E0' },
    { key: 'navy-200', hex: '#8FA8C0' },
    { key: 'navy-300', hex: '#5A7DA0' },
    { key: 'navy-400', hex: '#2D5380' },
    { key: 'navy-500', hex: '#0A2540' },
    { key: 'navy-600', hex: '#081E33' },
    { key: 'navy-700', hex: '#061626' },
    { key: 'navy-800', hex: '#040F1A' },
    { key: 'navy-900', hex: '#02070D' },
    // Teal
    { key: 'teal-300', hex: '#48CAE4' },
    { key: 'teal-400', hex: '#00B4D8' },
    { key: 'teal-600', hex: '#0096C7' },
    // Mint
    { key: 'mint-300', hex: '#52EFD0' },
    { key: 'mint-400', hex: '#00D4AA' },
    { key: 'mint-600', hex: '#00B892' },
    // Status
    { key: 'status-error',   hex: '#E63946' },
    { key: 'status-success', hex: '#10B981' },
    { key: 'status-warning', hex: '#F59E0B' },
    { key: 'status-info',    hex: '#00B4D8' },
  ]

  // Figma values override production palette where keys match; production fills the rest
  const figmaKeySet = new Set(figmaEntries.map((e) => e.key))
  const mergedPalette = [
    ...figmaEntries,
    ...productionPalette.filter((e) => !figmaKeySet.has(e.key)),
  ].sort((a, b) => a.key.localeCompare(b.key))

  const primitivesSource = `${banner(fileKey)}
//
// Merged: Figma-extracted brand colours + full production palette.
// When Figma adds more colour styles, re-run the script to sync.

export const colorPrimitives = {
  // ── From Figma ──────────────────────────────────────────────
${figmaEntries.map(({ key, hex }) => `  '${key}': '${hex}',`).join('\n')}

  // ── Production palette (base — not yet in Figma) ─────────────
${productionPalette.filter((e) => !figmaKeySet.has(e.key)).map(({ key, hex }) => `  '${key}': '${hex}',`).join('\n')}
}
`

  writeFileSync(resolve(TOKENS_DIR, 'color-primitives.js'), primitivesSource, 'utf8')
  console.log(`\n✅  Written: src/tokens/color-primitives.js  (${mergedPalette.length} colours)`)

  // ── 6. Write color-tokens.js ──────────────────────────────────────────
  //    For semantic tokens: try to reference a primitive with a matching hex;
  //    if no match found, fall back to the direct hex value.
  const hexToPrimitiveKey = {}
  for (const { key, hex } of primitiveEntries) {
    if (!hexToPrimitiveKey[hex]) hexToPrimitiveKey[hex] = key
  }

  const tokenLines = semanticEntries.map(({ key, hex }) => {
    const primitiveKey = hexToPrimitiveKey[hex]
    return primitiveKey
      ? `  '${key}': p['${primitiveKey}'],      // → ${hex}`
      : `  '${key}': '${hex}',                  // no matching primitive`
  })

  // If no semantic tokens found, keep existing file
  if (tokenLines.length === 0) {
    console.log(`ℹ️   No semantic colour tokens detected — color-tokens.js unchanged.`)
    console.log(`    (No style names matched semantic keywords: bg, text, border, surface, etc.)`)
  } else {
    const tokensSource = `${banner(fileKey)}

import { colorPrimitives as p } from './color-primitives.js'

export const colorTokens = {
${tokenLines.join('\n')}
}
`

    writeFileSync(resolve(TOKENS_DIR, 'color-tokens.js'), tokensSource, 'utf8')
    console.log(`✅  Written: src/tokens/color-tokens.js      (${tokenLines.length} semantic tokens)`)
  }

  // ── 7. Print a summary of what was found ─────────────────────────────
  console.log('\n── Colour Primitives ──────────────────────────────────────')
  for (const { key, hex } of primitiveEntries) {
    console.log(`   ${key.padEnd(28)} ${hex}`)
  }

  if (semanticEntries.length > 0) {
    console.log('\n── Semantic Tokens ────────────────────────────────────────')
    for (const { key, hex } of semanticEntries) {
      const alias = hexToPrimitiveKey[hex] ? ` → ${hexToPrimitiveKey[hex]}` : ''
      console.log(`   ${key.padEnd(28)} ${hex}${alias}`)
    }
  }

  console.log(`\n🎉  Done. Run \`npm run build\` to verify.\n`)
}

main().catch((err) => {
  console.error('Unexpected error:', err)
  process.exit(1)
})
