// AUTO-GENERATED by scripts/figma-import.mjs, DO NOT EDIT MANUALLY
// Last synced: 2026-04-13T12:33:24.533Z
// Source file: 7qgKd6B2j32HNeCHTExSRl

import { colorPrimitives as p } from './color-primitives.js'

export const colorTokens = {
  'brand-blue': '#5BA3D1',                  // no matching primitive
  'brand-dark-green': '#51B198',                  // no matching primitive
  'brand-logo-dark': '#4C5664',                  // no matching primitive
  'brand-orange': '#FF8A3E',                  // no matching primitive
  'brand-white': p['white'],      // → #FFFFFF
}
